/*
 * Maya-Exana — Bulk Export.
 * Generates N unique, printable exam papers from one blueprint + a master
 * grading key, as a single self-contained HTML file (open -> Print -> PDF).
 *
 * Zero dependencies, by design: we emit print-optimized HTML with one paper
 * per page. This proves the engine is usable in a real, offline classroom:
 *   node export.js 50            -> exports/exam_pack.html (50 papers + key)
 *   node export.js 30 myseed     -> 30 papers seeded from "myseed-0001"...
 *
 * Scaling: the CLI uses streamExamPack(), which writes each page to disk as it
 * is generated (fs.createWriteStream) instead of building one giant string in
 * memory. This handles institutional-scale exports (tens of thousands of
 * candidates) without an out-of-memory crash. buildExamPack() returns the same
 * document as a string for the in-memory/test path.
 */
const fs = require('fs');
const path = require('path');
const Aegis = require('./src/engine.js');

const DEFAULT_BLUEPRINT = [
  { templateId: 'percentage', points: 1 },
  { templateId: 'speed_dst', points: 1 },
  { templateId: 'compound_interest', points: 2 },
  { templateId: 'kinematics', points: 2 },
  { templateId: 'geometry_svg', points: 2 },
  { templateId: 'synonym', points: 1 },
  { templateId: 'big_o', points: 1 },
];

function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

const STYLE = `
  *{box-sizing:border-box}
  body{font:13px/1.5 Georgia,'Times New Roman',serif;color:#111;margin:0;background:#e9e9ee}
  .page{background:#fff;width:210mm;min-height:297mm;margin:10mm auto;padding:18mm 16mm;
    box-shadow:0 2px 10px rgba(0,0,0,.15)}
  .ph{display:flex;justify-content:space-between;align-items:baseline;border-bottom:2px solid #111;padding-bottom:8px;margin-bottom:6px}
  .pt{font-size:18px;font-weight:bold;letter-spacing:.5px}
  .pm{font-size:11px;color:#333}
  .note{font-size:11px;font-style:italic;color:#555;margin-bottom:14px}
  .q{margin:0 0 14px;page-break-inside:avoid}
  .qhead{font-size:12px} .subj{color:#555} .pts{float:right;color:#777;font-size:11px}
  .prompt{margin:3px 0 6px;font-size:14px}
  .fig{margin:6px 0}
  .opts{margin:4px 0 0 4px;padding:0;list-style:none}
  .opts li{margin:3px 0} .ol{display:inline-block;width:18px;font-weight:bold}
  .pf{margin-top:20px;border-top:1px solid #ccc;padding-top:6px;font-size:10px;color:#888;text-align:center}
  .key{font-family:Arial,sans-serif}
  .keytbl{width:100%;border-collapse:collapse;font-size:11px;margin-top:10px}
  .keytbl th,.keytbl td{border:1px solid #999;padding:4px 6px;text-align:center}
  .keytbl th{background:#111;color:#fff}
  .keytbl .kc{text-align:left;font-weight:bold}
  .toolbar{position:sticky;top:0;background:#111;color:#fff;padding:10px 16px;display:flex;
    justify-content:space-between;align-items:center;font-family:Arial,sans-serif}
  .toolbar button{background:#5b8cff;color:#fff;border:0;padding:8px 16px;border-radius:6px;font-weight:bold;cursor:pointer}
  @media print{ .toolbar{display:none} .page{box-shadow:none;margin:0;width:auto;min-height:auto}
    .page{page-break-after:always} }`;

function docHead(title, count) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<title>${esc(title)} — Exam Pack (${count})</title>
<style>${STYLE}</style></head><body>
<div class="toolbar"><span>Maya-Exana Exam Pack · ${count} unique papers + master key</span>
  <button onclick="window.print()">Print / Save as PDF</button></div>
`;
}
const docFoot = '\n</body></html>';

// One candidate's paper, as an HTML string.
function paperPage(id, exam, title) {
  const items = exam.items.map((it) => {
    const fig = it.svg ? `<div class="fig">${it.svg}</div>` : '';
    const opts = it.options
      .map((o, oi) => `<li><span class="ol">${String.fromCharCode(65 + oi)}.</span> ${esc(o)}${it.unit ? ' ' + esc(it.unit) : ''}</li>`)
      .join('');
    return `<div class="q">
      <div class="qhead"><b>${it.id}.</b> <span class="subj">${esc(it.subject)}</span>
        <span class="pts">[${it.points} ${it.points === 1 ? 'mark' : 'marks'}]</span></div>
      <div class="prompt">${esc(it.prompt)}</div>${fig}
      <ol class="opts" type="A">${opts}</ol>
    </div>`;
  }).join('');
  return `<section class="page paper">
    <header class="ph">
      <div class="pt">${esc(title)}</div>
      <div class="pm">Candidate: <b>${esc(id)}</b> · Total: ${exam.totalPoints} marks · Paper ID: ${esc(exam.studentSeed)}</div>
    </header>
    <div class="note">Every candidate's paper is uniquely generated. Answer all questions on the OMR sheet.</div>
    ${items}
    <footer class="pf">Generated by Maya-Exana · reproducible from Paper ID for audit</footer>
  </section>`;
}

// One row of the master key, as an HTML string.
function keyRow(id, exam) {
  return `<tr><td class="kc">${esc(id)}</td>${exam.items.map((it) => `<td>${String.fromCharCode(65 + it.correctIndex)}</td>`).join('')}</tr>`;
}

// In-memory build (used by tests and small exports).
function buildExamPack(studentIds, blueprint = DEFAULT_BLUEPRINT, title = 'Maya-Exana Examination') {
  const exams = studentIds.map((id) => ({ id, exam: Aegis.generateExam(blueprint, id) }));
  let out = docHead(title, exams.length);
  for (const { id, exam } of exams) out += paperPage(id, exam, title);
  const keyHeader = exams[0].exam.items.map((it) => `<th>${it.id}</th>`).join('');
  out += `<section class="page key">
    <header class="ph"><div class="pt">${esc(title)} — MASTER GRADING KEY</div>
      <div class="pm">CONFIDENTIAL · ${exams.length} candidates</div></header>
    <table class="keytbl"><thead><tr><th>Candidate</th>${keyHeader}</tr></thead><tbody>`;
  for (const { id, exam } of exams) out += keyRow(id, exam);
  out += `</tbody></table>
    <footer class="pf">Maya-Exana master key · each paper is reproducible from its Paper ID</footer>
  </section>`;
  return out + docFoot;
}

// Streaming build: write each page to disk as it is generated, so memory use
// stays flat regardless of cohort size. Returns a Promise.
function streamExamPack(studentIds, outPath, blueprint = DEFAULT_BLUEPRINT, title = 'Maya-Exana Examination') {
  return new Promise((resolve, reject) => {
    const ws = fs.createWriteStream(outPath, { encoding: 'utf8' });
    ws.on('error', reject);

    // Backpressure-aware writer: pause generation if the buffer fills.
    function write(chunk) {
      return new Promise((res) => { if (!ws.write(chunk)) ws.once('drain', res); else res(); });
    }

    (async () => {
      await write(docHead(title, studentIds.length));
      // Buffer key rows in a small array (one short string per student) and
      // emit papers immediately so full papers never accumulate in memory.
      const keyRows = [];
      let headerCols = '';
      for (const id of studentIds) {
        const exam = Aegis.generateExam(blueprint, id);
        if (!headerCols) headerCols = exam.items.map((it) => `<th>${it.id}</th>`).join('');
        await write(paperPage(id, exam, title));
        keyRows.push(keyRow(id, exam));
      }
      await write(`<section class="page key">
    <header class="ph"><div class="pt">${esc(title)} — MASTER GRADING KEY</div>
      <div class="pm">CONFIDENTIAL · ${studentIds.length} candidates</div></header>
    <table class="keytbl"><thead><tr><th>Candidate</th>${headerCols}</tr></thead><tbody>`);
      for (const row of keyRows) await write(row);
      await write(`</tbody></table>
    <footer class="pf">Maya-Exana master key · each paper is reproducible from its Paper ID</footer>
  </section>`);
      await write(docFoot);
      ws.end(resolve);
    })().catch(reject);
  });
}

// CLI — uses the streaming path so it scales without OOM.
if (require.main === module) {
  const n = Math.max(1, parseInt(process.argv[2] || '50', 10));
  const prefix = process.argv[3] || 'student';
  const ids = Array.from({ length: n }, (_, i) => `${prefix}-${String(i + 1).padStart(4, '0')}`);
  const outDir = path.join(__dirname, 'exports');
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, 'exam_pack.html');
  streamExamPack(ids, outPath)
    .then(() => {
      console.log(`Exported ${n} unique papers + master key -> ${path.relative(process.cwd(), outPath)} (streamed)`);
      console.log('Open it in a browser and click "Print / Save as PDF".');
    })
    .catch((e) => { console.error('Export failed:', e.message); process.exit(1); });
}

module.exports = { buildExamPack, streamExamPack, DEFAULT_BLUEPRINT };
